### PR TITLE
adding specs for new GenomeAnnotation and Assembly types

### PR DESCRIPTION
**Pull request by realmarcin**

### CODE REVIEW

**Comment by msneddon** [comment]
It looks like these are the uploaders for the new Genome types?  I think you have them tested already in CI, but are they ready now to be tested on next and go out on the next release (meaning are all the dependencies for the new data type deployed to next)?  Has anyone reviewed the documentation for the new methods?

**Comment by realmarcin** [comment]
OK, thanks -- yes, these are tested in CI though this code update is not an
exact mirror of CI so will need to test more.

Where do the docs for these methods live? I can take a look.

**Comment by mlhenderson** [comment]
@msneddon Transform includes these uploaders and Jason has registered the new types in Next.  We had registered these in the narrative_method_specs_ci repo, which I thought was where they were supposed to go.  Since that didn't propagate here, we don't have an identical repo, but the uploaders have been tested quite a bit in CI.

If there are problems getting this merged, if you can be explicit and specific about what is preventing the PR from being merged, those can be addressed.

**Comment by msneddon** [comment]
@mlhenderson- That's all fine, I just wanted to be sure this is ready to go out to next before I accepted, especially since new methods are involved.  There wasn't any description in the PR.  Accepting this also puts the new methods in the line to go to production, which I think we have planned to update at least once before the larger March release.  And before it goes to prod, of course, we need at least a basic review of the documentation.  If these are ready for review, please create a ticket for @nlharris and she can reassign as needed.  narrative_method_specs_ci was the right place to put the specs for testing and development in CI, but changes there do not automatically get propagated to next and production.

If you are ready to test on next, but want to hold off on production release until just before March (e.g. to coincide with a narrative release), let's switch this PR to the next branch.  When it's ready, we can then put a new PR into develop->staging->master line.  We can push method specs out basically immediately from there, but that way this change won't hold up any other updates to production that are for docs or other reviewed methods that we need to get out sooner.  For instance, this is what we are doing for the SDK helper methods- they are in the next branch only for now, and will need additional review/testing and another PR before we put them in the develop->staging->master line.

So let me know what you think.

**Comment by mlhenderson** [comment]
Ok, marcin should submit to the next branch then.  I can create a ticket
for nomi regarding the documentation.

Thanks

**Comment by msneddon** [comment]
Great, thanks.  I'm closing this for now, but once it's tested on next and ready to go on to staging, we can reopen or create a new PR.

**Comment by realmarcin** [comment]
I tested on next and:

1) assembly upload worked fine
2) genomannotation upload gives errors (tried 3 diff files) and a new error
that I haven't seen before:

Error:
usage: /kb/deployment/pybin/trns_transform_Genbank_Genome_to_KBaseGenomeAnnotations_GenomeAnnotation.py
       [-h] --shock_service_url [SHOCK_SERVICE_URL] --handle_service_url
       [HANDLE_SERVICE_URL] --workspace_name [WORKSPACE_NAME]
       [--taxon_wsname [TAXON_WSNAME]] [--taxon_reference [TAXON_REFERENCE]]
       --workspace_service_url [WORKSPACE_SERVICE_URL]
       [--object_name [OBJECT_NAME]] [--source [SOURCE]] [--type [TYPE]]
       --input_directory [INPUT_DIRECTORY]
/kb/deployment/pybin/trns_transform_Genbank_Genome_to_KBaseGenomeAnnotations_GenomeAnnotation.py:
error: argument --handle_service_url is required

**Pull request closed without merging**
