### PR TITLE
removed boxplot from viewers catergory. Turns out needed by some tutoria...

### PR DESCRIPTION
**Pull request by wilke**
...ls and tests.

### CODE REVIEW

**Comment by wilke** [comment]
Removing other viewer / updating descriptions / renaming method to address user feedback and errors

**Comment by wilke** [comment]
2) Explain the exact failure mode the change addresses:
- Removing viewers
- Reintroducing boxplot method (User did miss it) 
- Reformatting text in option description

3) Assess the risks associated with deploying the new code:
deployment on dev for testing - not production. 
yaml file might not work - and method not displayed 

4) Explain what tests you have done to make sure the code both fixes
the issue and doesn't break anything else:

Broken spec and yaml files did only break the method itself no side effects.
Verification and test on dev.

**Comment by msneddon** [comment]
See comments on https://github.com/kbase/narrative/pull/300, which is a related request.

**Comment by wilke** [comment]
Blocking "Create Metagenome from public data" method from being displayed.

**Comment by psdehal** [comment]
Andreas, I don't understand what you're doing here. It seems like you're taking an existing method "Communities Data Visualization" and renaming and having it do something completely different. Shouldn't you just add this as a new method? Doesn't this remove "Communities Data Visualization"? Was it not used?

**Comment by wilke** [comment]
Complicated:
- There has been some clean up and renaming. Basically the js code did query the api and created sets.
- The whole method in its current form is obsolete and not used. To hide it I added the "viewers" keyword to the category list in the method spec.

**Comment by psdehal** [comment]
Okay, but just to be clear, we aren't renaming methods anymore at the request of the docs team. If the method is obsolete, let's just delete it and then make sure the docs team removes it from their list of active methods.

**Comment by wilke** [comment]
I understand, the method is not tracked by the docs team and adding the viewers tag will effectively remove the method the method&app section. What is an alternative for the viewers tag to render the method inactive?

**Comment by psdehal** [comment]
If it's not tracked by docs team, shouldn't be displayed, is inactive and it's obsolete, then delete it. It's just adding clutter to the repo. When it's needed/fixed, we can add it back in, give it a better name and have it tracked by the docs team.

**Comment by wilke** [comment]
As you can see multiple changes. Major issue : Not tracked by the doc team but displayed. Other issue better option description for another method.

En route

**Comment by msneddon** [comment]
Got the go ahead to pull this in and have a look on narrative-dev.

**Comment by fperez** [comment]
It's Friday near noon.  I am very uncomfortable making any changes like this that will be user-visible at this point. 

The only question now is really: if we don't push this to production, does the entirety of KBase die and does everybody lose their job?

Unless the answer is "yes, everybody loses their job", this doesn't go into production.

**Comment by msneddon** [comment]
This is not going out to production, but there are are other doc changes in the tree that will need to make it out.  The only critical fix is that there is an obsolete method that should not be available to users.  That fix is solved by: https://github.com/kbase/narrative_method_specs/pull/199

So this PR is being reverted.

**Pull request merged**
