### PR TITLE
Fixes build species tree and compute pangenome specs

### PR DESCRIPTION
**Pull request by janakagithub**

### CODE REVIEW

**Comment by msneddon** [comment]
Why are we switching to GenomeSets?  Based on this thread KBASE-1166 and this PR https://github.com/kbase/narrative_method_specs, we are actually sticking with a list of genomes, and will not use GenomeSets at all...

**Comment by janakagithub** [comment]
So there was a discussion earlier to restore the GenomeSet type as it is more appropriate input for "computePanGenome" method. 

E-mail from Paramvir:
Yeah, I agree, we should leave genome set in. It seemed like it was going to be easier to simplify and remove it, but after a discussion with Janaka, it does have a lot of utility.

Let's restore the Insert Genome into Species Tree app and bring back the insert genomeset into Species Tree method as well.

On Fri, Jan 23, 2015 at 9:32 AM, Christopher Henry <chrisshenry@gmail.com> wrote:

    Hey guys,

    We’ve been going back and forth about genome sets, and I’m thinking increasingly that dropping them is a very bad idea.

    Now look, I was all on board with dropping them, and I apologize to Roman for pushing this, but I do think it’s a mistake.

    Rather, I think we need to do the following:

    1.) Change “Compute Pangenome” to take a genome set as input (this just involves a small change to method spec and NJS script, which I could have done today)
    2.) Restore the “tree to genome set method” and the “build species tree and genome set” app we had Roman remove yesterday (sorry roman)
    3.) Add a new method for building a genome set from genomes in the narrative (again, I think we already have this sitting around somewhere)
    4.) Have the tree app take a genome set as input instead of a single genome (this greatly improves its utility and we already have this sitting around somewhere)

    Matt and Janaka can push this in person, but I’ll just say I think this is the way to go…

    Chris

**Comment by olsonanl** [comment]
Is there going to be a mechanism to create a genome set from a set of genomes? One of the analyses I want to replicate in KB is the all-brucella comparisons that we do; it was very tedious to set up the pangenome computation by adding the genomes one at a time to the app, and if I want to ever do anything else what that set I’d need to reenter them all again.

On Jan 23, 2015, at 10:33 AM, janakagithub <notifications@github.com<mailto:notifications@github.com>> wrote:


So there was a discussion earlier to restore the GenomeSet type as it is more appropriate input for "computePanGenome" method.

E-mail from Paramvir:
Yeah, I agree, we should leave genome set in. It seemed like it was going to be easier to simplify and remove it, but after a discussion with Janaka, it does have a lot of utility.

Let's restore the Insert Genome into Species Tree app and bring back the insert genomeset into Species Tree method as well.

On Fri, Jan 23, 2015 at 9:32 AM, Christopher Henry chrisshenry@gmail.com<mailto:chrisshenry@gmail.com> wrote:

Hey guys,

We’ve been going back and forth about genome sets, and I’m thinking increasingly that dropping them is a very bad idea.

Now look, I was all on board with dropping them, and I apologize to Roman for pushing this, but I do think it’s a mistake.

Rather, I think we need to do the following:

1.) Change “Compute Pangenome” to take a genome set as input (this just involves a small change to method spec and NJS script, which I could have done today)
2.) Restore the “tree to genome set method” and the “build species tree and genome set” app we had Roman remove yesterday (sorry roman)
3.) Add a new method for building a genome set from genomes in the narrative (again, I think we already have this sitting around somewhere)
4.) Have the tree app take a genome set as input instead of a single genome (this greatly improves its utility and we already have this sitting around somewhere)

Matt and Janaka can push this in person, but I’ll just say I think this is the way to go…

Chris

**Comment by msneddon** [comment]
Ok- Chris's PR makes this change too, so I'm closing this.

**Pull request closed without merging**
