### PR TITLE
missing comma

### PR DESCRIPTION
**Pull request by teharrison**

### CODE REVIEW

**Comment by msneddon** [comment]
Please try to make sure things are working in sandbox first so we can avoid these types of errors.  That's what the sandbox is here for.

**Comment by jaredbischof** [comment]
I have a stupid question.  Why isn't the sandbox just a branch rather than
a separate repo in a separate organization?

**Comment by kkellerlbl** [comment]
I believe it's so that we can grant commit privileges to lots of people for the sandbox but keep commit privileges restricted for the production version.  As far as I can tell it is not possible in Github to allow access to certain branches but not others.

It could be in the KBase organization, true.  I think it's in Incubator to signify that it's not production code.

**Comment by jaredbischof** [comment]
Got it.

**Pull request merged**
