### PR TITLE
copy changes to modeling methods from narrative_method_specs_ci

### PR DESCRIPTION
**Pull request by mdejongh**

### CODE REVIEW

**Comment by msneddon** [comment]
Thanks @mdejongh!  Looks good and tests pass.  Since this is more than documentation, do the changes require that anything else be deployed to production/next for this to work?  Or is this ready to go out to Next now.  It seems like the main change is just to expose more parameters...

**Comment by mdejongh** [comment]
It should be ready to go to next. However, I do not know how long it has
been since the KBaseFBAModeling service (including MFAToolkit) on next has
been updated. There are bug fixes and improvements in this service on CI
that need to be pushed to next (and production) in conjunction with the UI
improvements.

Matt

On Wed, Jan 27, 2016 at 5:25 PM, Michael Sneddon <notifications@github.com>
wrote:

> Thanks @mdejongh <https://github.com/mdejongh>! Looks good and tests
> pass. Since this is more than documentation, do the changes require that
> anything else be deployed to production/next for this to work? Or is this
> ready to go out to Next now. It seems like the main change is just to
> expose more parameters...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbase/narrative_method_specs/pull/319#issuecomment-175891901>
> .
>



-- 
Matthew DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by msneddon** [comment]
Thanks Matt.  I'll sync up with others on the deployment status of FBA first then, but I think we will probably get this to next very soon.

**Comment by msneddon** [comment]
I pulled this in so we can take a look at it on next.  @mdejongh - can you please give the changes a try and see if it looks good there (should be ready on next in a few minutes)?  If so I'll get it on staging ready to go out with the next production deployments.

**Comment by mdejongh** [comment]
Changes to UI look good.

On Thu, Jan 28, 2016 at 5:48 PM, Michael Sneddon <notifications@github.com>
wrote:

> I pulled this in so we can take a look at it on next. @mdejongh
> <https://github.com/mdejongh> - can you please give the changes a try and
> see if it looks good there (should be ready on next in a few minutes)? If
> so I'll get it on staging ready to go out with the next production
> deployments.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbase/narrative_method_specs/pull/319#issuecomment-176465678>
> .
>



-- 
Matthew DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by msneddon** [comment]
Great, thanks for checking.  I migrated up to staging so this will go out next time we update the method specs.

**Pull request merged**
