### PR TITLE
Clarified JGI App

### PR DESCRIPTION
**Pull request by thebenallen**

### CODE REVIEW

**Comment by MrCreosote** [comment]
There's nothing JGI-specific about this app - it should work on any assembly FASTA file. It just happens that at the moment only JGI PtKB produces the KBaseFile.AssesmblyFile type.

**Comment by thebenallen** [comment]
Understandable - the basis of proposing these changes was this helpdesk ticket - https://atlassian.kbase.us/browse/KBASE-3757?jql=text%20~%20%22Convert%20Assembly%20File%20to%20Contigs%22

**Comment by MrCreosote** [comment]
That's fair enough. I'd just change the wording such that it says that currently PtKB is the only producer rather than the type is JGI-specific.

**Comment by thebenallen** [comment]
Ok thanks - I think it should be more clear now.

**Comment by thebenallen** [comment]
Just wanted to check on the status of this - I know that these app are being replaced with SDK ones soon. Will this text be migrated to the new app?

**Comment by MrCreosote** [comment]
@thebenallen the new repo is here: https://github.com/kbaseapps/gaprice_convert_assy_file_to_contigs, feel free to make a PR.

**Pull request merged**
