### PR TITLE
Update display.yaml

### PR DESCRIPTION
**Pull request by nlharris**
Added note that this is obsolete.

Really, this whole directory (import_contigset) should be deleted. I'm not sure how to do that via a PR.

Also, I'm confused because I thought I made this PR yesterday, but I don't see it.

### CODE REVIEW

**Comment by msneddon** [comment]
I know this is a trivial change, but can you please still update this PR to merge into develop instead of master?  Thanks.

**Comment by nlharris** [comment]
Ok, sorry, that was my mistake. Is there a way to move this commit to develop? Or should I just redo the PR in develop and you'll reject this one?

**Comment by msneddon** [comment]
I'm not sure if you can switch targets of an open PR- you may just have to close and reopen.

**Comment by nlharris** [comment]
Will re-do in develop.

**Pull request closed without merging**
