### PR TITLE
Remove obsolete method named 'data_visualization'

### PR DESCRIPTION
**Pull request by msneddon**
This method was marked as obsolete by its author (https://github.com/kbase/narrative_method_specs/pull/181#issuecomment-75147718), but only hidden in the narrative list by switching it to the viewer category.  However, this method still would appear on man pages (https://narrative-dev.kbase.us/functional-site/#/narrativestore/method/data_visualization) and other resources that look at the full list of methods.

This PR is related to changes from: https://github.com/kbase/narrative_method_specs/pull/181

### CODE REVIEW

**Comment by msneddon** [comment]
replaced by #201

**Comment by fperez** [comment]
So, should this be closed in favor of #201?

**Comment by msneddon** [comment]
Yep, this is closed.

**Comment by fperez** [comment]
oops, sorry, didn't see that :)

**Pull request closed without merging**
