### PR TITLE
Fixing text in description of display.yaml for annotate plant transcripts method

### PR DESCRIPTION
**Pull request by samseaver**

### CODE REVIEW

**Comment by msneddon** [comment]
Sorry I didn't notice this sooner, but I was about to accept and realized the PR is against 'dev' instead of 'develop'.  Can you please reissue the PR against 'develop'?  Thanks.

Otherwise this looks good, tests pass, and can go in.

**Comment by nlharris** [comment]
Sam, I just happened to see this--did you see Mike's request?

**Comment by samseaver** [comment]
I missed this, but I was trying to remember what it was we were doing. For some reason, the changes appear to be already present in develop

**Comment by msneddon** [comment]
Maybe it was updated independently by a separate docs team update?

I'm going to close this PR then because it seems the changes are already in place.  If that turns out to not  be the case, just open another PR against develop.  Thanks!

**Pull request closed without merging**
