### PR TITLE
abundance profile apps re-organized and merged

### PR DESCRIPTION
**Pull request by teharrison**

### CODE REVIEW

**Comment by teharrison** [comment]
This pull request has been updated with more changes after several apps were deleted.

**Comment by msneddon** [comment]
Have these been tested in narrative-sandbox?  Maybe I missed it, but I don't see the communities_build_taxonomic_profile and communities_build_functional_profile apps in:
https://github.com/kbaseIncubator/narrative_method_specs_sandbox

It would be best to at least see that the app/method specs parse and show up correctly there before we merge to the live method_specs repo...

**Comment by teharrison** [comment]
I didn't put them in there as the widget update is not propagated to the
narrative-sandbox, but I try as you suggest and just verify that the yaml
and spec files work correctly.

**Comment by teharrison** [comment]
I have a pull request here:
https://github.com/kbaseIncubator/narrative_method_specs_sandbox/pull/4

**Comment by teharrison** [comment]
ok, i have tested them in narrative-sandbox and they show up and run

**Comment by msneddon** [comment]
Great.  Sergei accepts the current state, and the docs team will return to revise the descriptions.

**Pull request merged**
