### PR TITLE
add media/model editors to develop

### PR DESCRIPTION
**Pull request by nconrad**

### CODE REVIEW

**Comment by msneddon** [comment]
@nconrad Has anyone reviewed the description and parameter name fields for this method, or have you asked them to yet?  It seems like they could use a lot of improvement.  Things like repeated short and long hints, numbers in the hints, and using ID in the parameter names...

Maybe @nlharris or @thebenallen can review the method and parameter descriptions here?

**Comment by cshenry** [comment]
You know they did actually look at these… but it was lumped into the SDK. So the changes didn’t get into the specs Neal has. If you guys have no objections, I’m thinking of just adding these specs to the fba_tools SDK… I think it’s going to make all of it easier to manage.

-- 
Chris Henry
Sent with Airmail

On March 2, 2016 at 5:14:28 PM, Michael Sneddon (notifications@github.com) wrote:

@nconrad Has anyone reviewed the description and parameter name fields for this method, or have you asked them to yet? It seems like they could use a lot of improvement. Things like repeated short and long hints, numbers in the hints, and using ID in the parameter names...

Maybe @nlharris or @thebenallen can review the method and parameter descriptions here?

**Comment by scanon** [comment]
That makes sense to me.

—Shane

**Comment by msneddon** [comment]
Great!  Let's add them to the fba_tools specs.

**Comment by cshenry** [comment]
OK. I’m doing it. And I just confirmed, the spreadsheet ben edited had these methods on it. In fact, ben suggested renaming the media method. Anyhow, I’m loading now with those altered parameters.

-- 
Chris Henry
Sent with Airmail

On March 2, 2016 at 5:28:18 PM, Shane Canon (notifications@github.com) wrote:


That makes sense to me.

—Shane

**Comment by nlharris** [comment]
Looks like this already got resolved, but I just wanted to mention the ticket https://atlassian.kbase.us/browse/KBASE-3673

**Pull request closed without merging**
