### PR TITLE
typo with categories for two methods

### PR DESCRIPTION
**Pull request by dcchivian**

### CODE REVIEW

**Comment by dcchivian** [comment]
added category-based KBase icons to KBase methods and TOOL to name so they will be easier to distinguish when we have multiple methods with different tools that perform similar analyses (also maintains branding and allows users to see "oh, they have X").

**Comment by dcchivian** [comment]
moved merge community model to metabolic_modeling as primary category

**Comment by dcchivian** [comment]
revised icons and method names to agreed upon form

**Comment by msneddon** [comment]
hmm, I think you probably should have made these changes on a clean branch.  I think all the name changes were reverted, but there are still other docs changes it looks like, and it is still picking up the old kbase icons that are not used.  It would be better to split this up into separate PRs, one clean one for just the icons, and another for any docs changes so we can accept each separately.  Sorry, I know this is probably a pain since you made changes directly in github...

**Comment by msneddon** [comment]
thanks. Aside from one minor addition, I think the remaining docs changes are all whitespace.  Travis is still churning though, so I'll wait for that to catch up.

**Comment by msneddon** [comment]
I'm just going to accept this without waiting for everything to complete.  You created a ton of travis jobs by making changes in a pending PR!

**Pull request merged**
