### PR TITLE
Urgent: So the URL validation performed in narrative is blocking my efforts to use the impl URL to induce the awe worker nodes to operate locally rather than using RPC calls. So I'm taking another tactic: using a constant parameter called "localmode" which I would alter the NJS job script to recognize. Can we check this in right away?

### PR DESCRIPTION
**Pull request by cshenry**
Urgent: So the URL validation performed in narrative is blocking my efforts to use the impl URL to induce the awe worker nodes to operate locally rather than using RPC calls. So I'm taking another tactic: using a constant parameter called "localmode" which I would alter the NJS job script to recognize. Can we check this in right away?

### CODE REVIEW

**Comment by psdehal** [comment]
Hey Adam and Fernando,

Chris has this post freeze PR. This fixes the issue that the runFBA method
has been running as a service instead of locally on the awe client. Chris
assures me that the code that is run is the exact same, so no additional
testing should be required. I'm going to merge it for now, we can undo the
merge if you guys think this is a mistake, but merging now will let Chris
continue working.

Paramvir

**Comment by psdehal** [comment]
Ok. I assume Chris will do basic testing and keep an eye. Do it. Gives us a couple days until launch.

Sent from mobile device and I have clumsy fingers.




On Tue, Feb 10, 2015 at 8:46 PM -0800, "Paramvir Dehal" <psdehal@lbl.gov> wrote:










Hey Adam and Fernando,
Chris has this post freeze PR. This fixes the issue that the runFBA method has been running as a service instead of locally on the awe client. Chris assures me that the code that is run is the exact same, so no additional testing should be required. I'm going to merge it for now, we can undo the merge if you guys think this is a mistake, but merging now will let Chris continue working.
Paramvir
On Tue, Feb 10, 2015 at 8:17 PM, cshenry <notifications@github.com> wrote:


Urgent: So the URL validation performed in narrative is blocking my efforts to use the impl URL to induce the awe worker nodes to operate locally rather than using RPC calls. So I'm taking another tactic: using a constant parameter called "localmode" which I would alter the NJS job script to recognize. Can we check this in right away?



You can view, comment on, or merge this pull request online at:


  https://github.com/kbase/narrative_method_specs/pull/167

Commit Summary

  Urgent: So the URL validation performed in narrative is blocking my efforts to use the impl URL to induce the awe worker nodes to operate locally rather than using RPC calls. So I'm taking another tactic: using a constant parameter called "localmode" which I would alter the NJS job script to recognize. Can we check this in right away?
  Merge branch 'dev' of https://github.com/kbase/narrative_method_specs into dev


File Changes

  
    M
    methods/run_flux_balance_analysis/spec.json
    (6)
  


Patch Links:

  https://github.com/kbase/narrative_method_specs/pull/167.patch
  https://github.com/kbase/narrative_method_specs/pull/167.diff

**Comment by psdehal** [comment]
I'm terrified of seeing code that introduces new parameters (which is an
extension of an API) without seeing a single test.  But that's "the KBase
way" for now...

So at least, please have Chris and at least someone else watch this thing
like a hawk, to catch any problems it may introduce right away...

Cheers,

f

**Comment by psdehal** [comment]
Yes, this will be a last minute change to the API and will require an
update to the NJS script on the other side. We'll do the testing to make
sure everything works as expected. It's always possible to have unintended
consequences, but it should be quick to flip the flag and revert the
previous state.

**Comment by cshenry** [comment]
So I've already run FBA on the dev post-merge, and everything is perfect. In fact, this actually fixed FBA, which was broken due to an invalid URL. 

The real test is going to happen when the NJS script gets updated. Once that happens, the new parameter will take effect and the jobs will run locally. I will watch closely, if it doesn't go well, we'll turn the new parameter "off". If it goes well, I'd like to turn it on for a few more of the modeling methods, as this will avoid any possibility of "timeouts" or overloading of the FBA server. Specifically, I'm worried about gapfilling and compute pangenome. If you gapfill a large community modeling, or you compute pangenome for many many genomes, this risks a timeout.

Extending the parameter should be low risk once we've fully tested it with FBA.

**Comment by cshenry** [comment]
Sorry, I wanted to get this done sooner, but I confess this really fell off my radar while I was focused on method and widget debugging earlier this week.

**Comment by psdehal** [comment]
Thanks Chris!

I'm just replying to add Adam, Fernando, et. al back to the email. I don't
think they're watchers on the specs repo.

**Pull request merged**
