### PR TITLE
added next steps to translate_model_to_new_genome

### PR DESCRIPTION
**Pull request by dcchivian**

### CODE REVIEW

**Comment by teharrison** [comment]
I enjoy spam as much as the next guy, but github allows you to send a pull request that includes multiple files. There is no need to do a separate pull request for each file, especially if the changes are related.  Note: I received 36 emails over ~1 hour for very related pull requests.

**Comment by psdehal** [comment]
thanks travis, that's good to know.

In this particular case, out of an abundance of caution,i asked dylan to
submit them individually so that I could test each change on dev and move
them independently to staging and master. Maybe i was being too cautious,
but I don't want there to be any chance something might break the day
before I leave for dc.

sorry for the inconvenience

**Comment by teharrison** [comment]
That's OK, I was just confused why so many separate PRs were made that were basically the same.  Sorry if I sounded grumpy but I just opened up my email browser to a large number of new emails and was going through them.  :)

**Comment by psdehal** [comment]
this is for the suggested next step and it only shows up after each
method/app runs so I've been running each app, it's taking awhile. and now
it seems like there's a problem with some of the awe clients...

**Comment by dcchivian** [comment]
Sorry everyone. Sorry everyone. Sorry everyone. Sorry everyone. Sorry
everyone. Sorry everyone. Sorry everyone. Sorry everyone. Sorry everyone.
Sorry everyone. Sorry everyone. Sorry everyone.
Sorry everyone. Sorry everyone. Sorry everyone. Sorry everyone. Sorry
everyone. Sorry everyone. Sorry everyone. Sorry everyone. Sorry everyone.
Sorry everyone. Sorry everyone. Sorry everyone.
Sorry everyone. Sorry everyone. Sorry everyone. Sorry everyone. Sorry
everyone. Sorry everyone. Sorry everyone. Sorry everyone. Sorry everyone.
Sorry everyone. Sorry everyone. Sorry everyone.

- dylan

**Pull request merged**
